name: flutter_user
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0-250.0.dev
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.1.0
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  firebase_database: ^11.3.0
  firebase_messaging: ^15.2.0
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  location: ^7.0.0
  audioplayers: ^6.0.0
  url_launcher: ^6.3.0
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.3.1
  flutter_contacts: ^1.1.9+2
  flutter_contacts_service: ^0.0.2
  share_plus: ^10.1.2
  connectivity_plus: ^6.0.5
  package_info_plus: ^4.1.0
  vector_math: ^2.1.4
  webview_flutter: ^4.2.4
  path_provider: ^2.1.4
  flutter_inappwebview: ^6.0.0
  uuid: ^4.4.2
  device_info_plus: ^10.1.2
  pinput: ^5.0.0
  intl: ^0.19.0
  animated_text_kit: ^4.2.2
  flutter_map: ^7.0.2
  carousel_slider: ^5.0.0
  latlong2: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/map_style_black.json
    - assets/dark.json




